# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19PQHXRsWqNudIghpnlKiHeAH06_sBPWj
"""

import streamlit as st
import pandas as pd

st.set_page_config(page_title="Lead Distribution Simulator", layout="wide")
st.title("🔁 Lead Distribution Simulator")

# Step 1: Setup session state if not already done
if "configured" not in st.session_state:
    st.sidebar.header("Simulation Settings")
    st.session_state.num_clients = st.sidebar.number_input("Number of Clients", min_value=2, max_value=20, value=3)
    st.session_state.num_rounds = st.sidebar.number_input("Number of Rounds", min_value=1, value=5)

    st.sidebar.header("Weights (Must sum to 1)")
    st.session_state.w_cpl = st.sidebar.slider("CPL Weight", 0.0, 1.0, 0.25)
    st.session_state.w_budget = st.sidebar.slider("Budget Utilization Weight", 0.0, 1.0, 0.5)
    st.session_state.w_time = round(1.0 - (st.session_state.w_cpl + st.session_state.w_budget), 2)
    st.sidebar.text(f"Recency Weight (auto): {st.session_state.w_time}")

    st.subheader("📥 Enter Client Details")
    st.session_state.client_data = []
    for i in range(st.session_state.num_clients):
        with st.expander(f"Client {i+1}", expanded=True):
            cpl = st.number_input(f"Client {i+1} CPL Bid", key=f"cpl_{i}")
            budget = st.number_input(f"Client {i+1} Budget", key=f"budget_{i}")
            time_since_last = st.number_input(f"Client {i+1} Initial Time Since Last Lead (hrs)", key=f"time_{i}")
            st.session_state.client_data.append({
                'Client': f'Client {i+1}',
                'CPL': cpl,
                'Budget': budget,
                'Remaining Budget': budget,
                'Time Since Last Lead': time_since_last
            })

    if st.button("Run Simulation"):
        st.session_state.current_round = 1
        st.session_state.results = []
        st.session_state.configured = True
        st.query_params["started"] = "true"
        st.stop()

# Step 2: Run Simulation
if st.session_state.get("configured", False) and st.session_state.current_round <= st.session_state.num_rounds:
    r = st.session_state.current_round
    st.subheader(f"🔁 Round {r}")
    df = pd.DataFrame(st.session_state.client_data)
    df["Budget Utilization"] = 1 - (df["Remaining Budget"] / df["Budget"])
    df["norm_CPL"] = (df["CPL"] - df["CPL"].min()) / (df["CPL"].max() - df["CPL"].min() + 1e-6)
    df["norm_Recency"] = (df["Time Since Last Lead"] - df["Time Since Last Lead"].min()) / \
                         (df["Time Since Last Lead"].max() - df["Time Since Last Lead"].min() + 1e-6)
    df["Score"] = (1 - df["norm_CPL"]) * st.session_state.w_cpl + \
                  (1 - df["Budget Utilization"]) * st.session_state.w_budget + \
                  df["norm_Recency"] * st.session_state.w_time

    lead_winner_idx = df["Score"].idxmax()
    lead_winner = df.loc[lead_winner_idx, "Client"]
    df.at[lead_winner_idx, "Remaining Budget"] -= df.loc[lead_winner_idx, "CPL"]

    st.dataframe(df[["Client", "CPL", "Remaining Budget", "Time Since Last Lead", "Score"]])

    st.markdown("### ⏱️ Update Time Since Last Lead (in hours)")
    time_updates = []
    for i in range(len(df)):
        label = f"{df.loc[i, 'Client']} - {'🔔 Got Lead' if i == lead_winner_idx else ''}"
        val = st.number_input(f"{label}", key=f"round{r}_time_{i}", value=0.0)
        time_updates.append(val)

    if st.button("👉 Proceed to Next Round"):
        for i in range(len(df)):
            new_time = time_updates[i]
            if i == lead_winner_idx:
                df.at[i, "Time Since Last Lead"] = new_time
            else:
                df.at[i, "Time Since Last Lead"] += new_time

        # Save the round results
        for i in range(len(df)):
            st.session_state.results.append({
                "Round": r,
                "Client": df.loc[i, "Client"],
                "CPL": df.loc[i, "CPL"],
                "Remaining Budget": df.loc[i, "Remaining Budget"],
                "Time Since Last Lead": df.loc[i, "Time Since Last Lead"],
                "Score": df.loc[i, "Score"],
                "Got Lead": "Yes" if i == lead_winner_idx else "No"
            })

        # Update session client data
        for i in range(len(df)):
            st.session_state.client_data[i]["Remaining Budget"] = df.loc[i, "Remaining Budget"]
            st.session_state.client_data[i]["Time Since Last Lead"] = df.loc[i, "Time Since Last Lead"]

        st.session_state.current_round += 1
        st.query_params["round"] = str(st.session_state.current_round)
        st.rerun()

elif st.session_state.get("configured", False):
    st.success("✅ Simulation Complete!")
    result_df = pd.DataFrame(st.session_state.results)
    st.dataframe(result_df)
    csv = result_df.to_csv(index=False).encode('utf-8')
    st.download_button("📥 Download Results as CSV", data=csv, file_name="lead_simulation_results.csv", mime="text/csv")




